FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jdk-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN pip install --no-cache-dir \
    pyspark==4.2.0 \
    pyarrow \
    pandas \
    lakefs \
    mlflow \
    dagshub \
    boto3

COPY src/ /app/src/
COPY config/ /app/config/

ENV PYTHONPATH="/app"