apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fraud-detector-metrics
  namespace: kserve
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: fraud-detector
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s