import os
 
#lakeFS
LAKECTL_SERVER_ENDPOINT_URL = os.getenv("LAKECTL_SERVER_ENDPOINT_URL")
LAKECTL_CREDENTIALS_ACCESS_KEY_ID = os.getenv("LAKECTL_CREDENTIALS_ACCESS_KEY_ID")
LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY = os.getenv("LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY")
LAKEFS_REPO_NAME = os.getenv("LAKEFS_REPO_NAME")  # renamed from REPO_NAME -- was colliding with DagsHub's REPO_NAME
MAIN_BRANCH_NAME = os.getenv("MAIN_BRANCH_NAME")
FEATURES_BRANCH_NAME = os.getenv("FEATURES_BRANCH_NAME")
 
#DagsHub
DAGSHUB_REPO_OWNER = os.getenv("DAGSHUB_REPO_OWNER")
DAGSHUB_REPO_NAME = os.getenv("DAGSHUB_REPO_NAME")  # renamed from REPO_NAME
DAGSHUB_USER_TOKEN = os.getenv("DAGSHUB_USER_TOKEN")
 
#MinIO
MINIO_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT_URL")
MINIO_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY_ID")
MINIO_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_ACCESS_KEY")
BUCKET_NAME = os.getenv("BUCKET_NAME")

#Non Sensitive Constants
RAW_DATA_DIR = "raw"
CLEANED_DATA_DIR = "cleaned"
TRANSFORMED_DATA_DIR = "transformed"
DATA_MODE = "latest_only"
COST_PER_MISSED_FRAUD = 5.0
COST_PER_BLOCKED_LEGIT_CUSTOMER = 1.0